[project]
name = "ff-winners-and-losers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "espn-api>=0.45.1",
    "pandas>=2.3.3",
]
